# Generated by Django 4.0.3 on 2022-04-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
